name: Build & Publish

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check prettier
        run: npm run prettier:check

      - name: Check eslint
        run: npm run lint:check

      - name: Check typescript
        run: npm run ts:check

      - name: Build package
        run: npm run build

      - name: Publish npm packages / create github release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
