name: Build & Publish

on:
  push:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check eslint
        run: npm run lint:check

      - name: Check typescript
        run: npm run ts:check

      - name: Run tests
        run: npx nyc npm run test

      - name: Build package
        run: npm run build

      - name: Archive code coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-artifacts
          path: |
            coverage/*

      - name: Publish npm packages / create github release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


  sonarcube:
    name: Sonarcube
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@master
        with:
          name: coverage-artifacts
          path: coverage

      - name: Get npm package version
        id: package-version
        uses: Saionaro/extract-package-version@v1.1.1
        with:
          path: ${{ env.WORK_DIR }}

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          projectBaseDir: ${{ env.WORK_DIR }}
          args: >
            -Dsonar.projectVersion=${{ steps.package-version.outputs.version }}
